name: llrm
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.1.2
  - torchvision=0.16.2
  - pytorch-cuda=12.1
  - numpy=1.24.4
  - pillow=10.4.0
  - opencv=4.10.0
  - scikit-image=0.21.0
  - scikit-learn=1.3.2
  - matplotlib=3.7.*
  - pyyaml=6.0.2
  - cuda-toolkit=12.1
  - cuda-nvcc
  - ffmpeg
  - pip
  - pip:
    - packaging==24.2
    - typing-extensions==4.12.2
    - easydict==1.13
    - kornia==0.7.3
    - wandb==0.19.1
    - einops==0.8.0
    - lpips==0.1.4
    - jaxtyping==0.2.19
    - termcolor==2.4.0
    - plyfile==1.0.3
    - opencv-python
    - videoio==0.3.0
    - ffmpeg-python==0.2.0
    - xformers==0.0.23.post1
    - causal-conv1d==1.4.0
    - mamba-ssm==2.2.2
